project_id = "deyvmtncimmcinldjyqe"

[functions.verify-discord-member]
enabled = true
verify_jwt = true
import_map = "./functions/verify-discord-member/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/verify-discord-member/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/verify-discord-member/*.html" ]

[functions.list-gallery-review-queue]
enabled = true
verify_jwt = true
import_map = "./functions/list-gallery-review-queue/deno.json"
entrypoint = "./functions/list-gallery-review-queue/index.ts"

[functions.moderate-gallery-submission]
enabled = true
verify_jwt = true
import_map = "./functions/moderate-gallery-submission/deno.json"
entrypoint = "./functions/moderate-gallery-submission/index.ts"

[functions.list-approved-gallery-submissions]
enabled = true
verify_jwt = false
import_map = "./functions/list-approved-gallery-submissions/deno.json"
entrypoint = "./functions/list-approved-gallery-submissions/index.ts"

[functions.submit-discord-gallery-image]
enabled = true
verify_jwt = false
import_map = "./functions/submit-discord-gallery-image/deno.json"
entrypoint = "./functions/submit-discord-gallery-image/index.ts"

[functions.reaper-discord-interactions]
enabled = true
verify_jwt = false
import_map = "./functions/reaper-discord-interactions/deno.json"
entrypoint = "./functions/reaper-discord-interactions/index.ts"

[functions.list-instagram-publish-queue]
enabled = true
verify_jwt = true
import_map = "./functions/list-instagram-publish-queue/deno.json"
entrypoint = "./functions/list-instagram-publish-queue/index.ts"

[functions.publish-instagram-gallery-submission]
enabled = true
verify_jwt = true
import_map = "./functions/publish-instagram-gallery-submission/deno.json"
entrypoint = "./functions/publish-instagram-gallery-submission/index.ts"
