version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      root-production-minor-and-patch:
        dependency-type: production
        update-types:
          - minor
          - patch
      root-development-minor-and-patch:
        dependency-type: development
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /apps/web
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      web-production-minor-and-patch:
        dependency-type: production
        update-types:
          - minor
          - patch
      web-development-minor-and-patch:
        dependency-type: development
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: eslint
        update-types:
          - version-update:semver-major
      - dependency-name: typescript
        update-types:
          - version-update:semver-major

  - package-ecosystem: npm
    directory: /apps/shopify-theme
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      theme-development-minor-and-patch:
        dependency-type: development
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: npm
    directory: /services/social
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      social-production-minor-and-patch:
        dependency-type: production
        update-types:
          - minor
          - patch
      social-development-minor-and-patch:
        dependency-type: development
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
      - dependency-name: webgl-media-editor
        versions:
          - ">=0.1.0"
      - dependency-name: webpack
        versions:
          - ">=5.107.0"

  - package-ecosystem: composer
    directory: /services/social
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      social-composer-production-minor-and-patch:
        dependency-type: production
        update-types:
          - minor
          - patch
      social-composer-development-minor-and-patch:
        dependency-type: development
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: docker
    directory: /services/social
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "serversideup/php"
        versions:
          - ">=8.5"

  - package-ecosystem: docker-compose
    directory: /services/social
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: mariadb
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
      - dependency-name: redis
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
