import { runCheckSuite } from "./lib/check-runner.mjs";

const checks = [
  ["check:js", ["node", "scripts/check-js.mjs"]],
  ["check:json", ["node", "scripts/check-json.mjs"]],
  ["check:protected-content", ["node", "scripts/check-protected-content.mjs"]],
  ["check:recruitment-audio-player", ["node", "scripts/check-recruitment-audio-player.mjs"]],
  ["check:content", ["node", "scripts/check-content-guardrails.mjs"]],
  ["check:code-cleanliness", ["node", "scripts/check-code-cleanliness.mjs"]],
  ["check:supabase-config", ["node", "scripts/check-supabase-public-config.mjs"]],
  ["check:discord-gallery-ingest", ["node", "scripts/check-discord-gallery-ingest.mjs"]],
  ["check:discord-reaper-parity", ["node", "scripts/check-discord-reaper-parity.mjs"]],
  ["check:discord-event-covers", ["node", "scripts/check-discord-event-covers.mjs"]],
  ["check:reaper-discord-interactions", ["node", "scripts/check-reaper-discord-interactions.mjs"]],
  ["test:photo-day-poll", ["deno", "test", "--allow-env", "--node-modules-dir=auto", "--import-map=supabase/functions/reaper-discord-interactions/deno.json", "--lock=deno.lock", "--frozen=true", "supabase/functions/_shared/photo-day-polls_test.ts"]],
  ["test:discord-signature", ["deno", "test", "--allow-env", "--node-modules-dir=auto", "--import-map=supabase/functions/reaper-discord-interactions/deno.json", "--lock=deno.lock", "--frozen=true", "supabase/functions/_shared/discord-signature_test.ts"]],
  ["test:reaper-discord-events", ["deno", "test", "--allow-env", "--node-modules-dir=auto", "--import-map=supabase/functions/reaper-discord-interactions/deno.json", "--lock=deno.lock", "--frozen=true", "supabase/functions/_shared/reaper-discord-events_test.ts"]],
  ["check:reaper-modmail-audit", ["node", "scripts/check-reaper-modmail-audit.mjs"]],
  ["test:reaper-pending-verification", ["deno", "test", "--lock=deno.lock", "--frozen=true", "supabase/functions/_shared/pending-verification-containment_test.ts"]],
  ["check:vote-reminder", ["node", "scripts/check-vote-reminder.mjs"]],
  ["check:instagram-gallery-publishing", ["node", "scripts/check-instagram-gallery-publishing.mjs"]],
  ["check:member-profiles-and-ranks", ["node", "scripts/check-member-profiles-and-ranks.mjs"]],
  ["check:member-workflow-qa", ["node", "scripts/check-member-workflow-qa.mjs"]],
  ["check:multi-provider-auth", ["node", "scripts/check-multi-provider-auth.mjs"]],
  ["check:apple-auth-readiness", ["node", "scripts/check-apple-auth-readiness.mjs"]],
  ["check:auth-provider-state-cleanup", ["node", "scripts/check-auth-provider-state-cleanup.mjs"]],
  ["check:mochi-pets-alpha", ["node", "scripts/check-mochi-pets-alpha.mjs"]],
  ["check:mochi-pets-auth-bridge", ["node", "scripts/check-mochi-pets-auth-bridge.mjs"]],
  ["check:mochi-pets-bridge-state", ["node", "scripts/check-mochi-pets-bridge-state.mjs"]],
  ["check:mochi-pets-browser-gates", ["node", "scripts/check-mochi-pets-browser-gate-self-test.mjs"]],
  ["check:mochi-pets-discord-oauth", ["node", "scripts/check-mochi-pets-discord-oauth-self-test.mjs"]],
  ["check:mochi-pets-edge-authority", ["node", "scripts/check-mochi-pets-edge-authority.mjs"]],
  ["test:mochi-pets-alpha", ["deno", "test", "--allow-env", "--node-modules-dir=auto", "--import-map=supabase/functions/mochi-pets-unity-auth/deno.json", "--lock=deno.lock", "--frozen=true", "supabase/functions/_shared/mochi-pets-alpha_test.ts"]],
  ["test:pixelfed-social-sync", ["deno", "test", "--allow-env", "--node-modules-dir=auto", "--import-map=supabase/functions/sync-pixelfed-social-account/deno.json", "--lock=deno.lock", "--frozen=true", "supabase/functions/_shared/pixelfed-social-sync_test.ts"]],
  ["check:mochi-pets-game-contract", ["node", "scripts/check-mochi-pets-game-contract.mjs"]],
  ["check:mochi-pets-preview-key-loader", ["node", "scripts/check-mochi-pets-preview-key-loader.mjs"]],
  ["check:mochi-pets-preview-url", ["node", "scripts/check-mochi-pets-preview-url-self-test.mjs"]],
  ["check:mochi-pets-rename-manifest", ["node", "scripts/check-mochi-pets-rename-manifest.mjs"]],
  ["check:mochi-pets-tester-password-gate", ["node", "scripts/check-mochi-pets-tester-password-gate.mjs"]],
  ["check:mochi-pets-report-hygiene", ["node", "scripts/check-mochi-pets-report-hygiene.mjs"]],
  ["smoke:mochi-pets-alpha-edge", ["node", "scripts/smoke-mochi-pets-alpha-edge.mjs"]],
  ["check:supabase-edge-types", ["node", "scripts/check-supabase-edge-types.mjs"]],
  ["check:cutover-validators", ["node", "scripts/check-cutover-validator-self-tests.mjs"]],
  ["check:gallery-approved-feed", ["node", "scripts/check-gallery-approved-feed.mjs"]],
  ["check:gallery-timestamps", ["node", "scripts/check-gallery-timestamps.mjs"]],
  ["check:media-performance", ["node", "scripts/check-media-performance.mjs"]],
  ["check:guild-schedule", ["node", "scripts/check-guild-schedule.mjs"]],
  ["check:home-celebration-splash", ["node", "scripts/check-home-celebration-splash.mjs"]],
  ["check:events-page-schedule-sync", ["node", "scripts/check-events-page-schedule-sync.mjs"]],
  ["check:observability-metadata-smoke", ["node", "scripts/check-observability-metadata-smoke.mjs"]],
  ["check:full-stack-release-evidence", ["node", "scripts/check-full-stack-release-evidence.mjs"]],
  ["check:csp-inline-hardening", ["node", "scripts/check-csp-inline-hardening.mjs"]],
  ["check:accessibility-route-matrix", ["node", "scripts/check-accessibility-route-matrix.mjs"]],
  ["check:pixelfed-oidc-spike", ["node", "scripts/check-pixelfed-oidc-spike.mjs"]],
  ["check:pixelfed-first-login-readiness", ["node", "scripts/check-pixelfed-first-login-readiness.mjs"]],
  ["check:shop-brand", ["node", "scripts/check-shop-brand-guardrails.mjs"]],
  ["check:site-navigation", ["node", "scripts/check-site-navigation.mjs"]],
  ["check:supabase-security-performance", ["node", "scripts/check-supabase-security-performance.mjs"]],
  ["check:security-hardening", ["node", "scripts/check-security-hardening.mjs"]],
  ["check:spotlight-poll", ["node", "scripts/check-spotlight-poll.mjs"]],
  ["check:refs", ["node", "scripts/check-refs.mjs"]],
  ["check:assets", ["node", "scripts/check-assets.mjs"]],
  ["check:next-public-sync", ["node", "scripts/check-next-public-sync.mjs"]],
  ["check:universal-hero-spacing", ["node", "scripts/check-universal-hero-spacing.mjs"]],
];

if (!runCheckSuite(checks)) {
  console.error("\nValidation failed.");
  process.exit(1);
}

console.log("\nAll validation checks completed.");
