export const SPINNER_PROXY_UPSTREAM_TIMEOUT_MS = 12_000;
export const SPINNER_BROWSER_REQUEST_TIMEOUT_MS = 16_000;
export const SPINNER_RESPONSE_MARGIN_MS =
  SPINNER_BROWSER_REQUEST_TIMEOUT_MS - SPINNER_PROXY_UPSTREAM_TIMEOUT_MS;
